/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	v1 "k8s.io/application-aware-controller/pkg/apis/appawarecontroller/v1"
	"k8s.io/client-go/tools/cache"
)

// AppawareHorizontalPodAutoscalerLister helps list AppawareHorizontalPodAutoscalers.
// All objects returned here must be treated as read-only.
type AppawareHorizontalPodAutoscalerLister interface {
	// List lists all AppawareHorizontalPodAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AppawareHorizontalPodAutoscaler, err error)
	// AppawareHorizontalPodAutoscalers returns an object that can list and get AppawareHorizontalPodAutoscalers.
	AppawareHorizontalPodAutoscalers(namespace string) AppawareHorizontalPodAutoscalerNamespaceLister
	AppawareHorizontalPodAutoscalerListerExpansion
}

// appawareHorizontalPodAutoscalerLister implements the AppawareHorizontalPodAutoscalerLister interface.
type appawareHorizontalPodAutoscalerLister struct {
	indexer cache.Indexer
}

// NewAppawareHorizontalPodAutoscalerLister returns a new AppawareHorizontalPodAutoscalerLister.
func NewAppawareHorizontalPodAutoscalerLister(indexer cache.Indexer) AppawareHorizontalPodAutoscalerLister {
	return &appawareHorizontalPodAutoscalerLister{indexer: indexer}
}

// List lists all AppawareHorizontalPodAutoscalers in the indexer.
func (s *appawareHorizontalPodAutoscalerLister) List(selector labels.Selector) (ret []*v1.AppawareHorizontalPodAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AppawareHorizontalPodAutoscaler))
	})
	return ret, err
}

// AppawareHorizontalPodAutoscalers returns an object that can list and get AppawareHorizontalPodAutoscalers.
func (s *appawareHorizontalPodAutoscalerLister) AppawareHorizontalPodAutoscalers(namespace string) AppawareHorizontalPodAutoscalerNamespaceLister {
	return appawareHorizontalPodAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AppawareHorizontalPodAutoscalerNamespaceLister helps list and get AppawareHorizontalPodAutoscalers.
// All objects returned here must be treated as read-only.
type AppawareHorizontalPodAutoscalerNamespaceLister interface {
	// List lists all AppawareHorizontalPodAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.AppawareHorizontalPodAutoscaler, err error)
	// Get retrieves the AppawareHorizontalPodAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.AppawareHorizontalPodAutoscaler, error)
	AppawareHorizontalPodAutoscalerNamespaceListerExpansion
}

// appawareHorizontalPodAutoscalerNamespaceLister implements the AppawareHorizontalPodAutoscalerNamespaceLister
// interface.
type appawareHorizontalPodAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AppawareHorizontalPodAutoscalers in the indexer for a given namespace.
func (s appawareHorizontalPodAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1.AppawareHorizontalPodAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.AppawareHorizontalPodAutoscaler))
	})
	return ret, err
}

// Get retrieves the AppawareHorizontalPodAutoscaler from the indexer for a given namespace and name.
func (s appawareHorizontalPodAutoscalerNamespaceLister) Get(name string) (*v1.AppawareHorizontalPodAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("appawarehorizontalpodautoscaler"), name)
	}
	return obj.(*v1.AppawareHorizontalPodAutoscaler), nil
}
