/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	appawarecontrollerv1 "k8s.io/application-aware-controller/pkg/apis/appawarecontroller/v1"
	testing "k8s.io/client-go/testing"
)

// FakeResourcesWarmupActuators implements ResourcesWarmupActuatorInterface
type FakeResourcesWarmupActuators struct {
	Fake *FakeAppawarecontrollerV1
	ns   string
}

var resourceswarmupactuatorsResource = schema.GroupVersionResource{Group: "appawarecontroller.k8s.io", Version: "v1", Resource: "resourceswarmupactuators"}

var resourceswarmupactuatorsKind = schema.GroupVersionKind{Group: "appawarecontroller.k8s.io", Version: "v1", Kind: "ResourcesWarmupActuator"}

// Get takes name of the resourcesWarmupActuator, and returns the corresponding resourcesWarmupActuator object, and an error if there is any.
func (c *FakeResourcesWarmupActuators) Get(ctx context.Context, name string, options v1.GetOptions) (result *appawarecontrollerv1.ResourcesWarmupActuator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourceswarmupactuatorsResource, c.ns, name), &appawarecontrollerv1.ResourcesWarmupActuator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ResourcesWarmupActuator), err
}

// List takes label and field selectors, and returns the list of ResourcesWarmupActuators that match those selectors.
func (c *FakeResourcesWarmupActuators) List(ctx context.Context, opts v1.ListOptions) (result *appawarecontrollerv1.ResourcesWarmupActuatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourceswarmupactuatorsResource, resourceswarmupactuatorsKind, c.ns, opts), &appawarecontrollerv1.ResourcesWarmupActuatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appawarecontrollerv1.ResourcesWarmupActuatorList{ListMeta: obj.(*appawarecontrollerv1.ResourcesWarmupActuatorList).ListMeta}
	for _, item := range obj.(*appawarecontrollerv1.ResourcesWarmupActuatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourcesWarmupActuators.
func (c *FakeResourcesWarmupActuators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourceswarmupactuatorsResource, c.ns, opts))

}

// Create takes the representation of a resourcesWarmupActuator and creates it.  Returns the server's representation of the resourcesWarmupActuator, and an error, if there is any.
func (c *FakeResourcesWarmupActuators) Create(ctx context.Context, resourcesWarmupActuator *appawarecontrollerv1.ResourcesWarmupActuator, opts v1.CreateOptions) (result *appawarecontrollerv1.ResourcesWarmupActuator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourceswarmupactuatorsResource, c.ns, resourcesWarmupActuator), &appawarecontrollerv1.ResourcesWarmupActuator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ResourcesWarmupActuator), err
}

// Update takes the representation of a resourcesWarmupActuator and updates it. Returns the server's representation of the resourcesWarmupActuator, and an error, if there is any.
func (c *FakeResourcesWarmupActuators) Update(ctx context.Context, resourcesWarmupActuator *appawarecontrollerv1.ResourcesWarmupActuator, opts v1.UpdateOptions) (result *appawarecontrollerv1.ResourcesWarmupActuator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourceswarmupactuatorsResource, c.ns, resourcesWarmupActuator), &appawarecontrollerv1.ResourcesWarmupActuator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ResourcesWarmupActuator), err
}

// Delete takes name of the resourcesWarmupActuator and deletes it. Returns an error if one occurs.
func (c *FakeResourcesWarmupActuators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(resourceswarmupactuatorsResource, c.ns, name), &appawarecontrollerv1.ResourcesWarmupActuator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourcesWarmupActuators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourceswarmupactuatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appawarecontrollerv1.ResourcesWarmupActuatorList{})
	return err
}

// Patch applies the patch and returns the patched resourcesWarmupActuator.
func (c *FakeResourcesWarmupActuators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appawarecontrollerv1.ResourcesWarmupActuator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourceswarmupactuatorsResource, c.ns, name, pt, data, subresources...), &appawarecontrollerv1.ResourcesWarmupActuator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ResourcesWarmupActuator), err
}
