/*
Copyright The KubeEdge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	appawarecontrollerv1 "github.com/kubeedge/sedna/pkg/apis/appawarecontroller/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppawareHorizontalPodAutoscalers implements AppawareHorizontalPodAutoscalerInterface
type FakeAppawareHorizontalPodAutoscalers struct {
	Fake *FakeAppawarecontrollerV1
	ns   string
}

var appawarehorizontalpodautoscalersResource = schema.GroupVersionResource{Group: "appawarecontroller.k8s.io", Version: "v1", Resource: "appawarehorizontalpodautoscalers"}

var appawarehorizontalpodautoscalersKind = schema.GroupVersionKind{Group: "appawarecontroller.k8s.io", Version: "v1", Kind: "AppawareHorizontalPodAutoscaler"}

// Get takes name of the appawareHorizontalPodAutoscaler, and returns the corresponding appawareHorizontalPodAutoscaler object, and an error if there is any.
func (c *FakeAppawareHorizontalPodAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appawarehorizontalpodautoscalersResource, c.ns, name), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscaler), err
}

// List takes label and field selectors, and returns the list of AppawareHorizontalPodAutoscalers that match those selectors.
func (c *FakeAppawareHorizontalPodAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *appawarecontrollerv1.AppawareHorizontalPodAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appawarehorizontalpodautoscalersResource, appawarehorizontalpodautoscalersKind, c.ns, opts), &appawarecontrollerv1.AppawareHorizontalPodAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appawarecontrollerv1.AppawareHorizontalPodAutoscalerList{ListMeta: obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscalerList).ListMeta}
	for _, item := range obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appawareHorizontalPodAutoscalers.
func (c *FakeAppawareHorizontalPodAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appawarehorizontalpodautoscalersResource, c.ns, opts))

}

// Create takes the representation of a appawareHorizontalPodAutoscaler and creates it.  Returns the server's representation of the appawareHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeAppawareHorizontalPodAutoscalers) Create(ctx context.Context, appawareHorizontalPodAutoscaler *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, opts v1.CreateOptions) (result *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appawarehorizontalpodautoscalersResource, c.ns, appawareHorizontalPodAutoscaler), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscaler), err
}

// Update takes the representation of a appawareHorizontalPodAutoscaler and updates it. Returns the server's representation of the appawareHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeAppawareHorizontalPodAutoscalers) Update(ctx context.Context, appawareHorizontalPodAutoscaler *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, opts v1.UpdateOptions) (result *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appawarehorizontalpodautoscalersResource, c.ns, appawareHorizontalPodAutoscaler), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppawareHorizontalPodAutoscalers) UpdateStatus(ctx context.Context, appawareHorizontalPodAutoscaler *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, opts v1.UpdateOptions) (*appawarecontrollerv1.AppawareHorizontalPodAutoscaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(appawarehorizontalpodautoscalersResource, "status", c.ns, appawareHorizontalPodAutoscaler), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscaler), err
}

// Delete takes name of the appawareHorizontalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeAppawareHorizontalPodAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appawarehorizontalpodautoscalersResource, c.ns, name), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppawareHorizontalPodAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appawarehorizontalpodautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appawarecontrollerv1.AppawareHorizontalPodAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched appawareHorizontalPodAutoscaler.
func (c *FakeAppawareHorizontalPodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appawarecontrollerv1.AppawareHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appawarehorizontalpodautoscalersResource, c.ns, name, pt, data, subresources...), &appawarecontrollerv1.AppawareHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareHorizontalPodAutoscaler), err
}
