/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	appawarecontrollerv1 "k8s.io/application-aware-controller/pkg/apis/appawarecontroller/v1"
	testing "k8s.io/client-go/testing"
)

// FakeAppawareClusterAutoscalers implements AppawareClusterAutoscalerInterface
type FakeAppawareClusterAutoscalers struct {
	Fake *FakeAppawarecontrollerV1
	ns   string
}

var appawareclusterautoscalersResource = schema.GroupVersionResource{Group: "appawarecontroller.k8s.io", Version: "v1", Resource: "appawareclusterautoscalers"}

var appawareclusterautoscalersKind = schema.GroupVersionKind{Group: "appawarecontroller.k8s.io", Version: "v1", Kind: "AppawareClusterAutoscaler"}

// Get takes name of the appawareClusterAutoscaler, and returns the corresponding appawareClusterAutoscaler object, and an error if there is any.
func (c *FakeAppawareClusterAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *appawarecontrollerv1.AppawareClusterAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appawareclusterautoscalersResource, c.ns, name), &appawarecontrollerv1.AppawareClusterAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareClusterAutoscaler), err
}

// List takes label and field selectors, and returns the list of AppawareClusterAutoscalers that match those selectors.
func (c *FakeAppawareClusterAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *appawarecontrollerv1.AppawareClusterAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appawareclusterautoscalersResource, appawareclusterautoscalersKind, c.ns, opts), &appawarecontrollerv1.AppawareClusterAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appawarecontrollerv1.AppawareClusterAutoscalerList{ListMeta: obj.(*appawarecontrollerv1.AppawareClusterAutoscalerList).ListMeta}
	for _, item := range obj.(*appawarecontrollerv1.AppawareClusterAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appawareClusterAutoscalers.
func (c *FakeAppawareClusterAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appawareclusterautoscalersResource, c.ns, opts))

}

// Create takes the representation of a appawareClusterAutoscaler and creates it.  Returns the server's representation of the appawareClusterAutoscaler, and an error, if there is any.
func (c *FakeAppawareClusterAutoscalers) Create(ctx context.Context, appawareClusterAutoscaler *appawarecontrollerv1.AppawareClusterAutoscaler, opts v1.CreateOptions) (result *appawarecontrollerv1.AppawareClusterAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appawareclusterautoscalersResource, c.ns, appawareClusterAutoscaler), &appawarecontrollerv1.AppawareClusterAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareClusterAutoscaler), err
}

// Update takes the representation of a appawareClusterAutoscaler and updates it. Returns the server's representation of the appawareClusterAutoscaler, and an error, if there is any.
func (c *FakeAppawareClusterAutoscalers) Update(ctx context.Context, appawareClusterAutoscaler *appawarecontrollerv1.AppawareClusterAutoscaler, opts v1.UpdateOptions) (result *appawarecontrollerv1.AppawareClusterAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appawareclusterautoscalersResource, c.ns, appawareClusterAutoscaler), &appawarecontrollerv1.AppawareClusterAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareClusterAutoscaler), err
}

// Delete takes name of the appawareClusterAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeAppawareClusterAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appawareclusterautoscalersResource, c.ns, name), &appawarecontrollerv1.AppawareClusterAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppawareClusterAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appawareclusterautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appawarecontrollerv1.AppawareClusterAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched appawareClusterAutoscaler.
func (c *FakeAppawareClusterAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appawarecontrollerv1.AppawareClusterAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appawareclusterautoscalersResource, c.ns, name, pt, data, subresources...), &appawarecontrollerv1.AppawareClusterAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.AppawareClusterAutoscaler), err
}
