/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	appawarecontrollerv1 "k8s.io/application-aware-controller/pkg/apis/appawarecontroller/v1"
	testing "k8s.io/client-go/testing"
)

// FakeForecastPolicies implements ForecastPolicyInterface
type FakeForecastPolicies struct {
	Fake *FakeAppawarecontrollerV1
	ns   string
}

var forecastpoliciesResource = schema.GroupVersionResource{Group: "appawarecontroller.k8s.io", Version: "v1", Resource: "forecastpolicies"}

var forecastpoliciesKind = schema.GroupVersionKind{Group: "appawarecontroller.k8s.io", Version: "v1", Kind: "ForecastPolicy"}

// Get takes name of the forecastPolicy, and returns the corresponding forecastPolicy object, and an error if there is any.
func (c *FakeForecastPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *appawarecontrollerv1.ForecastPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(forecastpoliciesResource, c.ns, name), &appawarecontrollerv1.ForecastPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ForecastPolicy), err
}

// List takes label and field selectors, and returns the list of ForecastPolicies that match those selectors.
func (c *FakeForecastPolicies) List(ctx context.Context, opts v1.ListOptions) (result *appawarecontrollerv1.ForecastPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(forecastpoliciesResource, forecastpoliciesKind, c.ns, opts), &appawarecontrollerv1.ForecastPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appawarecontrollerv1.ForecastPolicyList{ListMeta: obj.(*appawarecontrollerv1.ForecastPolicyList).ListMeta}
	for _, item := range obj.(*appawarecontrollerv1.ForecastPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested forecastPolicies.
func (c *FakeForecastPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(forecastpoliciesResource, c.ns, opts))

}

// Create takes the representation of a forecastPolicy and creates it.  Returns the server's representation of the forecastPolicy, and an error, if there is any.
func (c *FakeForecastPolicies) Create(ctx context.Context, forecastPolicy *appawarecontrollerv1.ForecastPolicy, opts v1.CreateOptions) (result *appawarecontrollerv1.ForecastPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(forecastpoliciesResource, c.ns, forecastPolicy), &appawarecontrollerv1.ForecastPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ForecastPolicy), err
}

// Update takes the representation of a forecastPolicy and updates it. Returns the server's representation of the forecastPolicy, and an error, if there is any.
func (c *FakeForecastPolicies) Update(ctx context.Context, forecastPolicy *appawarecontrollerv1.ForecastPolicy, opts v1.UpdateOptions) (result *appawarecontrollerv1.ForecastPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(forecastpoliciesResource, c.ns, forecastPolicy), &appawarecontrollerv1.ForecastPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ForecastPolicy), err
}

// Delete takes name of the forecastPolicy and deletes it. Returns an error if one occurs.
func (c *FakeForecastPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(forecastpoliciesResource, c.ns, name), &appawarecontrollerv1.ForecastPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeForecastPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(forecastpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &appawarecontrollerv1.ForecastPolicyList{})
	return err
}

// Patch applies the patch and returns the patched forecastPolicy.
func (c *FakeForecastPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *appawarecontrollerv1.ForecastPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(forecastpoliciesResource, c.ns, name, pt, data, subresources...), &appawarecontrollerv1.ForecastPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appawarecontrollerv1.ForecastPolicy), err
}
