/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v1 "k8s.io/application-aware-controller/pkg/apis/appawarecontroller/v1"
	scheme "k8s.io/application-aware-controller/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

// ResourceRecommendationsGetter has a method to return a ResourceRecommendationInterface.
// A group's client should implement this interface.
type ResourceRecommendationsGetter interface {
	ResourceRecommendations(namespace string) ResourceRecommendationInterface
}

// ResourceRecommendationInterface has methods to work with ResourceRecommendation resources.
type ResourceRecommendationInterface interface {
	Create(ctx context.Context, resourceRecommendation *v1.ResourceRecommendation, opts metav1.CreateOptions) (*v1.ResourceRecommendation, error)
	Update(ctx context.Context, resourceRecommendation *v1.ResourceRecommendation, opts metav1.UpdateOptions) (*v1.ResourceRecommendation, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ResourceRecommendation, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ResourceRecommendationList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceRecommendation, err error)
	ResourceRecommendationExpansion
}

// resourceRecommendations implements ResourceRecommendationInterface
type resourceRecommendations struct {
	client rest.Interface
	ns     string
}

// newResourceRecommendations returns a ResourceRecommendations
func newResourceRecommendations(c *AppawarecontrollerV1Client, namespace string) *resourceRecommendations {
	return &resourceRecommendations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceRecommendation, and returns the corresponding resourceRecommendation object, and an error if there is any.
func (c *resourceRecommendations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ResourceRecommendation, err error) {
	result = &v1.ResourceRecommendation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceRecommendations that match those selectors.
func (c *resourceRecommendations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ResourceRecommendationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ResourceRecommendationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceRecommendations.
func (c *resourceRecommendations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a resourceRecommendation and creates it.  Returns the server's representation of the resourceRecommendation, and an error, if there is any.
func (c *resourceRecommendations) Create(ctx context.Context, resourceRecommendation *v1.ResourceRecommendation, opts metav1.CreateOptions) (result *v1.ResourceRecommendation, err error) {
	result = &v1.ResourceRecommendation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceRecommendation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a resourceRecommendation and updates it. Returns the server's representation of the resourceRecommendation, and an error, if there is any.
func (c *resourceRecommendations) Update(ctx context.Context, resourceRecommendation *v1.ResourceRecommendation, opts metav1.UpdateOptions) (result *v1.ResourceRecommendation, err error) {
	result = &v1.ResourceRecommendation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		Name(resourceRecommendation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceRecommendation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the resourceRecommendation and deletes it. Returns an error if one occurs.
func (c *resourceRecommendations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceRecommendations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcerecommendations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched resourceRecommendation.
func (c *resourceRecommendations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceRecommendation, err error) {
	result = &v1.ResourceRecommendation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcerecommendations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
